[project]
name = "rinha-backend-2026-python"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "msgspec==0.19.0",
    "numpy==2.2.5",
    "robyn==0.81.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = ["-p", "no:cacheprovider"]
